{% set version = "0.3.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-censored
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/censored_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/censored/censored_{{ version }}.tar.gz
  sha256: 3f7bac6a67609a3a2bce717f29ec862fad1a4b18b282dd058ae8a246bc752b9c

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-dials
    - r-dplyr >=0.8.0.1
    - r-generics
    - r-glue
    - r-hardhat >=1.1.0
    - r-lifecycle
    - r-mboost
    - r-parsnip >=1.1.0
    - r-prodlim >=2023.03.31
    - r-purrr
    - r-rlang >=1.0.0
    - r-survival >=3.3_1
    - r-tibble >=3.1.3
    - r-tidyr >=1.0.0
  run:
    - r-base
    - r-cli
    - r-dials
    - r-dplyr >=0.8.0.1
    - r-generics
    - r-glue
    - r-hardhat >=1.1.0
    - r-lifecycle
    - r-mboost
    - r-parsnip >=1.1.0
    - r-prodlim >=2023.03.31
    - r-purrr
    - r-rlang >=1.0.0
    - r-survival >=3.3_1
    - r-tibble >=3.1.3
    - r-tidyr >=1.0.0

test:
  commands:
    - $R -e "library('censored')"           # [not win]
    - "\"%R%\" -e \"library('censored')\""  # [win]

about:
  home: https://github.com/tidymodels/censored
  license: MIT
  summary: Engines for survival models from the 'parsnip' package. These include parametric models (e.g., Jackson (2016) <doi:10.18637/jss.v070.i08>), semi-parametric (e.g., Simon et al (2011) <doi:10.18637/jss.v039.i05>), and tree-based models (e.g., Buehlmann and Hothorn (2007) <doi:10.1214/07-STS242>).
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
